name: CI/CD - OTA Update

on:
  push:
    branches:
      - main

jobs:
  ota_update:
    name: OTA Update
    runs-on: ubuntu-latest
    steps:
      - name: Push OTA update
        run: eas update --branch production --message "Auto update" --non-interactive
